### ISSUE TITLE
AMI Image deep-learning-for-computer-vision-with-python not available anymore

### ISSUE THREAD

**Issue by jr-d3-data** [PyImageSearch/DL4CV#20]
_Please use this template while reporting bugs inside DL4CV. Issues related to personal project questions or code that we haven't authored will automatically be closed._

## Are you using one of our development environments? 
➡️ I try to, but its not available.

We provide a preconfigured AWS AMI and a VM to help our customers skip the environment setup part and jump straight to development. We highly suggest using one of our development environments to run our code. 

## Describe the issue 

➡️ in https://customers.pyimagesearch.com/supplementary-material-2/ the AMI image on AWS is mentioned.
when I now search it on AWS, it only says "not available" in the community marketplace.
please provide a new image or concise instructions on how to create an AWS image.

**Comment by vikaskookna** [comment]
Hi @jr-d3-data, this is a work in progress you can track this [thread](https://community.pyimagesearch.com/t/amazon-ami-for-dl4cvp-missing-in-aws/12368/15) for updates. We will fix this soon.
