### ISSUE TITLE
Failed to import Tensorflow in Ubuntu ---- Illegal Instruction (Core Dump) Error

### ISSUE THREAD

**Issue by DwayneAcosta** [PyImageSearch/DL4CV#24]
Hi, 

I've purchased the starter bundle for DL4CV and followed all the instructions in the Ubuntu Virtual Machine install guide but cant seem to install TensorFlow in Ubuntu.

It gives me the error Illegal Instruction (Core Dump).

Would like to ask for your help with this issue so I can continue with the rest of the book. 

Thanks!

**Comment by vikaskookna** [comment]
Hi @ArkmLine, this issue is most probably due to the less hardware memory and disk space please make sure you have enough memory released.
